# Generated by Django 5.1.2 on 2025-06-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pubData_RunData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Identifiers', models.CharField(max_length=1000)),
                ('Reference', models.CharField(max_length=100)),
                ('UserID', models.CharField(max_length=10)),
                ('Lab', models.CharField(max_length=100)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
