# Generated by Django 5.2.3 on 2025-07-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bioinformatics_APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubdata_rundata',
            name='Analysis',
            field=models.CharField(default='bulk-RNA-Seq', max_length=50),
            preserve_default=False,
        ),
    ]
